# Generate Archaic Dataframe and Splice Altering List

This notebook gathers the SpliceAI archaic annotations, combines the InDel and SNV data, adds additional information including the distribution of alternate alleles, gene constraint, mean gene conservation, and removes invariant sites.

Load library. Set the number of columns to be displayed to a large value.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 100)

Load indels.

In [2]:
indels_header = ['chrom','pos','ref_allele','altai_gt','denisovan_gt','vindija_gt','alt_allele','annotation','ag_delta','al_delta','dg_delta','dl_delta','ag_pos','al_pos','dg_pos','dl_pos']
indels = pd.read_csv('../../data/spliceai_outputs/spliceai_archaic_indels.txt', sep = '\t', names = indels_header)
indels.head(10)

,chrom,pos,ref_allele,altai_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,ag_pos,al_pos,dg_pos,dl_pos
0,chr1,739130,T,0/0,./.,0/1,TA,AL669831.1,0.00,0.00,0.00,0.00,-7,-36,-35,-31
1,chr1,739130,T,0/1,./.,0/0,TAA,AL669831.1,0.00,0.00,0.00,0.00,-31,-36,-7,-31
2,chr1,867993,GTTTC,1/1,./.,./.,G,SAMD11,0.00,0.06,0.00,0.00,-48,11,29,-7
3,chr1,868522,A,1/1,./.,1/1,AG,SAMD11,0.00,0.00,0.00,0.00,-33,2,-10,2
4,chr1,869121,T,./.,1/1,./.,TG,SAMD11,0.00,0.00,0.01,0.00,48,-36,-36,-41
5,chr1,869244,C,./.,1/1,./.,CAG,SAMD11,0.00,0.00,0.00,0.00,-3,33,23,33
6,chr1,870339,C,0/0,./.,./.,CA,SAMD11,0.00,0.00,0.00,0.01,-33,-5,-6,-34
7,chr1,870339,C,1/1,./.,./.,CG,SAMD11,0.00,0.00,0.00,0.00,-33,-5,-6,-34
8,chr1,872534,A,1/1,1/1,./.,AG,SAMD11,0.00,0.00,0.00,0.00,1,-32,-32,17
9,chr1,872776,GCC,./.,./.,./.,G,SAMD11,0.01,0.00,0.00,0.00,-14,18,-19,-14

Add a column for Chagyrskaya and the variant type.

In [3]:
indels['chagyrskaya_gt'] = './.'
indels['variant_type'] = 'indel'

Reorder columns so that the dataframe matches the SNV dataframe.

In [4]:
indels = indels[['chrom','pos','ref_allele','altai_gt','chagyrskaya_gt','denisovan_gt','vindija_gt','alt_allele','annotation','ag_delta','al_delta','dg_delta','dl_delta','ag_pos','al_pos','dg_pos','dl_pos','variant_type']]
indels.head(10)

,chrom,pos,ref_allele,altai_gt,chagyrskaya_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,ag_pos,al_pos,dg_pos,dl_pos,variant_type
0,chr1,739130,T,0/0,./.,./.,0/1,TA,AL669831.1,0.00,0.00,0.00,0.00,-7,-36,-35,-31,indel
1,chr1,739130,T,0/1,./.,./.,0/0,TAA,AL669831.1,0.00,0.00,0.00,0.00,-31,-36,-7,-31,indel
2,chr1,867993,GTTTC,1/1,./.,./.,./.,G,SAMD11,0.00,0.06,0.00,0.00,-48,11,29,-7,indel
3,chr1,868522,A,1/1,./.,./.,1/1,AG,SAMD11,0.00,0.00,0.00,0.00,-33,2,-10,2,indel
4,chr1,869121,T,./.,./.,1/1,./.,TG,SAMD11,0.00,0.00,0.01,0.00,48,-36,-36,-41,indel
5,chr1,869244,C,./.,./.,1/1,./.,CAG,SAMD11,0.00,0.00,0.00,0.00,-3,33,23,33,indel
6,chr1,870339,C,0/0,./.,./.,./.,CA,SAMD11,0.00,0.00,0.00,0.01,-33,-5,-6,-34,indel
7,chr1,870339,C,1/1,./.,./.,./.,CG,SAMD11,0.00,0.00,0.00,0.00,-33,-5,-6,-34,indel
8,chr1,872534,A,1/1,./.,1/1,./.,AG,SAMD11,0.00,0.00,0.00,0.00,1,-32,-32,17,indel
9,chr1,872776,GCC,./.,./.,./.,./.,G,SAMD11,0.01,0.00,0.00,0.00,-14,18,-19,-14,indel

Now load the SNVs.

In [5]:
snvs_header = ['chrom','pos','ref_allele','altai_gt','chagyrskaya_gt','denisovan_gt','vindija_gt','alt_allele','annotation','ag_delta','al_delta','dg_delta','dl_delta','ag_pos','al_pos','dg_pos','dl_pos']
snvs = pd.read_csv('../../data/spliceai_outputs/spliceai_archaic_snvs.txt', sep = '\t', names = snvs_header)
snvs.head(10)

,chrom,pos,ref_allele,altai_gt,chagyrskaya_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,ag_pos,al_pos,dg_pos,dl_pos
0,chr10,180887,C,0/0,./.,./.,0/0,A,ZMYND11,0.00,0.00,0.00,0.0,40,42,40,-2
1,chr10,180998,G,0/0,./.,./.,0/0,A,ZMYND11,0.00,0.00,0.00,0.0,2,12,35,0
2,chr10,181000,T,0/0,./.,./.,0/0,A,ZMYND11,0.00,0.00,0.01,0.0,-7,10,33,-2
3,chr10,182007,C,0/0,0/0,./.,./.,T,ZMYND11,0.00,0.00,0.00,0.0,-6,-24,40,-24
4,chr10,182073,C,1/1,0/0,0/0,0/0,T,ZMYND11,0.01,0.00,0.02,0.0,12,-46,11,2
5,chr10,183370,C,0/0,0/0,1/1,0/0,T,ZMYND11,0.00,0.00,0.00,0.0,-48,-30,-12,37
6,chr10,184616,T,1/1,1/1,0/0,1/1,G,ZMYND11,0.00,0.00,0.00,0.0,9,24,-1,3
7,chr10,185171,G,1/1,1/1,1/1,1/1,T,ZMYND11,0.01,0.00,0.00,0.0,38,1,37,-47
8,chr10,185264,G,0/0,0/0,1/1,0/0,A,ZMYND11,0.00,0.01,0.00,0.0,2,19,2,19
9,chr10,185358,C,1/1,1/1,1/1,1/1,T,ZMYND11,0.00,0.00,0.00,0.0,-41,-25,-29,-11

In [6]:
snvs['variant_type'] = 'snv'

Concat the dataframes.

In [7]:
data = pd.concat([indels, snvs], ignore_index = True)
data = data.sort_values(by = ['chrom', 'pos'])
data.head(10)

,chrom,pos,ref_allele,altai_gt,chagyrskaya_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,ag_pos,al_pos,dg_pos,dl_pos,variant_type
0,chr1,739130,T,0/0,./.,./.,0/1,TA,AL669831.1,0.0,0.0,0.00,0.0,-7,-36,-35,-31,indel
1,chr1,739130,T,0/1,./.,./.,0/0,TAA,AL669831.1,0.0,0.0,0.00,0.0,-31,-36,-7,-31,indel
1169649,chr1,861808,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.01,0.0,-29,-27,24,-20,snv
1169650,chr1,861808,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,48,-14,-46,-14,snv
1169651,chr1,862072,C,1/1,1/1,0/0,0/1,T,SAMD11,0.0,0.0,0.00,0.0,3,28,-38,41,snv
1169652,chr1,862072,C,1/1,1/1,0/0,0/1,T,AL645608.1,0.0,0.0,0.00,0.0,-6,-50,24,-48,snv
1169653,chr1,862093,T,0/0,0/0,1/1,0/0,C,SAMD11,0.0,0.0,0.00,0.0,7,14,-15,34,snv
1169654,chr1,862093,T,0/0,0/0,1/1,0/0,C,AL645608.1,0.0,0.0,0.00,0.0,-34,48,49,3,snv
1169655,chr1,862124,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.00,0.0,-24,26,-11,3,snv
1169656,chr1,862124,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,17,-14,-28,35,snv

In [8]:
len(data)

2269396

Now let's add columns to designate whether at least one alternate allele is present per individual using a boolean (>= 1 alternate allele present = TRUE).

In [9]:
data['altai_gt_boolean'] = data['altai_gt'].replace({'./.':'FALSE', '0/0':'FALSE', '1/1':'TRUE', '1/0':'TRUE', '0/1':'TRUE'})
data['chagyrskaya_gt_boolean'] = data['chagyrskaya_gt'].replace({'./.':'FALSE', '0/0':'FALSE', '1/1':'TRUE', '1/0':'TRUE', '0/1':'TRUE'})
data['denisovan_gt_boolean'] = data['denisovan_gt'].replace({'./.':'FALSE', '0/0':'FALSE', '1/1':'TRUE', '1/0':'TRUE', '0/1':'TRUE'})
data['vindija_gt_boolean'] = data['vindija_gt'].replace({'./.':'FALSE', '0/0':'FALSE', '1/1':'TRUE', '1/0':'TRUE', '0/1':'TRUE'})

Now that we know which archaics have at least one alternate allele, let's assign a distribution variable that indicates which archaics have one or two alternate alleles.

In [10]:
def distribution(data):
    
    if (data['altai_gt_boolean'] == 'TRUE') & (data['chagyrskaya_gt_boolean'] == 'FALSE') & (data['denisovan_gt_boolean'] == 'FALSE') & (data['vindija_gt_boolean'] == 'FALSE'):
        return 'Altai'
    elif (data['altai_gt_boolean'] == 'FALSE') & (data['chagyrskaya_gt_boolean'] == 'TRUE') & (data['denisovan_gt_boolean'] == 'FALSE') & (data['vindija_gt_boolean'] == 'FALSE'):
        return 'Chagyrskaya'
    elif (data['altai_gt_boolean'] == 'FALSE') & (data['chagyrskaya_gt_boolean'] == 'FALSE') & (data['denisovan_gt_boolean'] == 'TRUE') & (data['vindija_gt_boolean'] == 'FALSE'):
        return 'Denisovan'
    elif (data['altai_gt_boolean'] == 'FALSE') & (data['chagyrskaya_gt_boolean'] == 'FALSE') & (data['denisovan_gt_boolean'] == 'FALSE') & (data['vindija_gt_boolean'] == 'TRUE'):
        return 'Vindija'
    elif (data['altai_gt_boolean'] == 'TRUE') & (data['chagyrskaya_gt_boolean'] == 'TRUE') & (data['denisovan_gt_boolean'] == 'FALSE') & (data['vindija_gt_boolean'] == 'TRUE'):
        return 'Neanderthal'
    elif (data['altai_gt_boolean'] == 'FALSE') & (data['chagyrskaya_gt_boolean'] == 'TRUE') & (data['denisovan_gt_boolean'] == 'FALSE') & (data['vindija_gt_boolean'] == 'TRUE'):
        return 'Late Neanderthal'
    elif (data['altai_gt_boolean'] == 'TRUE') & (data['chagyrskaya_gt_boolean'] == 'FALSE') & (data['denisovan_gt_boolean'] == 'TRUE') & (data['vindija_gt_boolean'] == 'TRUE') & (data['variant_type'] == 'indel'):
        return 'Shared'
    elif (data['altai_gt_boolean'] == 'TRUE') & (data['chagyrskaya_gt_boolean'] == 'TRUE') & (data['denisovan_gt_boolean'] == 'TRUE') & (data['vindija_gt_boolean'] == 'TRUE') & (data['variant_type'] == 'snv'):
        return 'Shared'
    else:
        return 'Other'
    
data['distribution'] = data.apply(distribution, axis = 1)

Some rows may actually be invariant, likely because we set low quality genotypes to missing and/or invariant sites were included in the original data. We need to remove these rows.

In [11]:
data_drop_indices = data[ (data['altai_gt_boolean'] == 'FALSE') & (data['chagyrskaya_gt_boolean'] == 'FALSE') & (data['denisovan_gt_boolean'] == 'FALSE') & (data['vindija_gt_boolean'] == 'FALSE')].index
data.drop(data_drop_indices, inplace = True)

In [12]:
len(data)

2107054

In multiple downstream analyses, we will need the maximum delta value among AG, AL, DG, and DL. Let's add a row with that information now.

In [13]:
data['delta_max'] = data[['ag_delta','al_delta','dg_delta','dl_delta']].max(axis = 1)

Let's reorder the columns a bit so that value occurs near the other deltas.

In [14]:
data = data[['chrom','pos','ref_allele','altai_gt','chagyrskaya_gt','denisovan_gt','vindija_gt','alt_allele','annotation','ag_delta','al_delta','dg_delta','dl_delta','delta_max','ag_pos','al_pos','dg_pos','dl_pos','variant_type','altai_gt_boolean','chagyrskaya_gt_boolean','denisovan_gt_boolean','vindija_gt_boolean','distribution']]
data.head(10)

,chrom,pos,ref_allele,altai_gt,chagyrskaya_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,delta_max,ag_pos,al_pos,dg_pos,dl_pos,variant_type,altai_gt_boolean,chagyrskaya_gt_boolean,denisovan_gt_boolean,vindija_gt_boolean,distribution
0,chr1,739130,T,0/0,./.,./.,0/1,TA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-7,-36,-35,-31,indel,FALSE,FALSE,FALSE,TRUE,Vindija
1,chr1,739130,T,0/1,./.,./.,0/0,TAA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-31,-36,-7,-31,indel,TRUE,FALSE,FALSE,FALSE,Altai
1169649,chr1,861808,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.01,0.0,0.01,-29,-27,24,-20,snv,FALSE,FALSE,TRUE,FALSE,Denisovan
1169650,chr1,861808,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,0.00,48,-14,-46,-14,snv,FALSE,FALSE,TRUE,FALSE,Denisovan
1169651,chr1,862072,C,1/1,1/1,0/0,0/1,T,SAMD11,0.0,0.0,0.00,0.0,0.00,3,28,-38,41,snv,TRUE,TRUE,FALSE,TRUE,Neanderthal
1169652,chr1,862072,C,1/1,1/1,0/0,0/1,T,AL645608.1,0.0,0.0,0.00,0.0,0.00,-6,-50,24,-48,snv,TRUE,TRUE,FALSE,TRUE,Neanderthal
1169653,chr1,862093,T,0/0,0/0,1/1,0/0,C,SAMD11,0.0,0.0,0.00,0.0,0.00,7,14,-15,34,snv,FALSE,FALSE,TRUE,FALSE,Denisovan
1169654,chr1,862093,T,0/0,0/0,1/1,0/0,C,AL645608.1,0.0,0.0,0.00,0.0,0.00,-34,48,49,3,snv,FALSE,FALSE,TRUE,FALSE,Denisovan
1169655,chr1,862124,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.00,0.0,0.00,-24,26,-11,3,snv,FALSE,FALSE,TRUE,FALSE,Denisovan
1169656,chr1,862124,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,0.00,17,-14,-28,35,snv,FALSE,FALSE,TRUE,FALSE,Denisovan

Let's load some data on constraint at the gene-level and add four relevant ones to our dataframe: 1) missense observed/expected, 2) loss-of-function observed/expected, 3) missense z-score and 4)loss-of-function z-score.

In [15]:
constraint = pd.read_csv('../../data/annotations/gnomad.v2.1.1.lof_metrics.by_gene.txt', header = 0, sep = '\t')
constraint.head(10)

,gene,transcript,obs_mis,exp_mis,oe_mis,mu_mis,possible_mis,obs_mis_pphen,exp_mis_pphen,oe_mis_pphen,possible_mis_pphen,obs_syn,exp_syn,oe_syn,mu_syn,possible_syn,obs_lof,mu_lof,possible_lof,exp_lof,pLI,pNull,pRec,oe_lof,oe_syn_lower,oe_syn_upper,oe_mis_lower,oe_mis_upper,oe_lof_lower,oe_lof_upper,constraint_flag,syn_z,mis_z,lof_z,oe_lof_upper_rank,oe_lof_upper_bin,oe_lof_upper_bin_6,n_sites,classic_caf,max_af,no_lofs,obs_het_lof,obs_hom_lof,defined,p,exp_hom_lof,classic_caf_afr,classic_caf_amr,classic_caf_asj,classic_caf_eas,classic_caf_fin,classic_caf_nfe,classic_caf_oth,classic_caf_sas,p_afr,p_amr,p_asj,p_eas,p_fin,p_nfe,p_oth,p_sas,transcript_type,gene_id,transcript_level,cds_length,num_coding_exons,gene_type,gene_length,exac_pLI,exac_obs_lof,exac_exp_lof,exac_oe_lof,brain_expression,chromosome,start_position,end_position
0,MED13,ENST00000397786,871,1117.80,0.77921,0.000056,14195,314.0,529.75,0.59273,6708.0,422,387.53,1.08900,0.000019,4248,0.0,0.000005,1257.0,98.429,1.0,8.943600e-40,1.838300e-16,0.000000,1.005,1.180,0.736,0.824,0.000,0.030,NaN,-1.376500,2.6232,9.1935,0.0,0.0,0.0,2.0,0.000012,0.000008,124782.0,3.0,0.0,124785.0,0.000012,0.000018,0.000000,0.000000,0.000000,0.000000,0.000093,0.000009,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000093,0.000009,0.0,0.000000,protein_coding,ENSG00000108510,2,6522,30,protein_coding,122678,1.0,0.0,64.393,0.000000,NaN,17,60019966,60142643
1,NIPBL,ENST00000282516,846,1441.50,0.58688,0.000074,18540,158.0,543.10,0.29092,7135.0,496,495.01,1.00200,0.000025,5211,1.0,0.000009,1781.0,150.320,1.0,2.977300e-59,3.572400e-24,0.006653,0.930,1.079,0.554,0.621,0.001,0.032,NaN,-0.035119,5.5737,11.2860,1.0,0.0,0.0,2.0,0.000012,0.000008,125693.0,3.0,0.0,125696.0,0.000012,0.000018,0.000000,0.000000,0.000099,0.000000,0.000000,0.000000,0.0,0.000065,0.000000,0.000000,0.000099,0.000000,0.000000,0.000000,0.0,0.000065,protein_coding,ENSG00000164190,2,8412,46,protein_coding,189655,1.0,1.0,110.570,0.009044,NaN,5,36876861,37066515
2,SMC3,ENST00000361804,178,630.07,0.28251,0.000032,8109,21.0,182.52,0.11506,2197.0,215,203.25,1.05780,0.000010,2091,0.0,0.000005,937.0,79.490,1.0,2.785300e-32,2.191400e-13,0.000000,0.946,1.184,0.249,0.320,0.000,0.037,NaN,-0.647760,6.3999,8.2618,2.0,0.0,0.0,8.0,0.000032,0.000004,125731.0,8.0,0.0,125739.0,0.000032,0.000127,0.000000,0.000000,0.000099,0.000054,0.000000,0.000044,0.0,0.000033,0.000000,0.000000,0.000099,0.000054,0.000000,0.000044,0.0,0.000033,protein_coding,ENSG00000108055,2,3651,29,protein_coding,36946,1.0,0.0,58.523,0.000000,NaN,10,112327449,112364394
3,CNOT1,ENST00000317147,561,1295.90,0.43290,0.000069,15670,51.0,290.68,0.17545,3560.0,470,456.03,1.03060,0.000024,4564,1.0,0.000007,1440.0,125.030,1.0,2.992400e-49,4.562900e-20,0.007998,0.955,1.112,0.403,0.464,0.002,0.038,NaN,-0.514100,7.2546,10.2790,3.0,0.0,0.0,5.0,0.000020,0.000004,125740.0,4.0,0.0,125744.0,0.000016,0.000032,0.000000,0.000029,0.000000,0.000055,0.000000,0.000026,0.0,0.000000,0.000000,0.000029,0.000000,0.000054,0.000000,0.000018,0.0,0.000000,protein_coding,ENSG00000125107,2,7128,48,protein_coding,109936,1.0,3.0,90.130,0.033285,NaN,16,58553855,58663790
4,RLF,ENST00000372771,669,972.87,0.68766,0.000047,12682,107.0,321.14,0.33319,4151.0,358,352.62,1.01530,0.000017,3482,0.0,0.000004,1024.0,73.222,1.0,8.405500e-30,2.284200e-12,0.000000,0.930,1.108,0.645,0.733,0.000,0.040,NaN,-0.225180,3.4620,7.9294,4.0,0.0,0.0,1.0,0.000004,0.000004,125122.0,1.0,0.0,125123.0,0.000004,0.000002,0.000062,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000062,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,protein_coding,ENSG00000117000,2,5742,8,protein_coding,79549,1.0,0.0,43.607,0.000000,NaN,1,40627045,40706593
5,PCF11,ENST00000298281,574,783.46,0.73265,0.000039,10106,130.0,264.36,0.49176,3521.0,298,272.69,1.09280,0.000013,3026,0.0,0.000005,862.0,74.559,1.0,2.487200e-30,1.385500e-12,0.000000,0.993,1.203,0.683,0.785,0.000,0.040,NaN,-1.205000,2.6592,8.0014,5.0,0.0,0.0,4.0,0.000016,0.000004,124625.0,3.0,0.0,124628.0,0.000012,0.000018,0.000000,0.000000,0.000000,0.000111,0.000000,0.000018,0.0,0.000000,0.000000,0.000000,0.000000,0.000056,0.000000,0.000018,0.0,0.000000,protein_coding,ENSG00000165494,2,4665,16,protein_coding,30464,1.0,1.0,48.160,0.020764,NaN,11,82868030,82898493
6,FNDC3B,ENST00000336824,551,689.52,0.79911,0.000038,7833,75.0,160.48,0.46735,1794.0,274,265.93,1.03040,0.000017,2360,0.0,0.000004,805.0,69.811,1.0,1.879200e-28,8.179200e-12,0.000000,0.933,1.139,0.744,0.857,0.000,0.042,NaN,-0.389080,1.8745,7.7425,6.0,0.0,0.0,2.0,0.000008,0.000004,125745.0,2.0,0.0,125747.0,0.000008,0.000008,0.000000,0.000029,0.000000,0.000000,0.000000,0.000009,0.0,0.000000,0.000000,0.000029,0.000000,0.000000,0.000000,0.000009,0.0,0.000000,protein_coding,ENSG00000075420,2,3612,25,protein_coding,362038,1.0,0.0,49.447,0.000000,NaN,3,171757418,172119455
7,TAF1,ENST00000276072,326,748.30,0.43565,0.000060,12563,82.0,312.02,0.26280,5365.0,272,250.43,1.08610,0.000018,3522,0.0,0.000005,1203.0,68.906,1.0,4.288100e-28,1.147700e-11,0.000000,0.983,1.201,0.397,0.477,0.000,0.043,NaN,-1.071200,5.4860,7.6921,7.0,0.0,0.0,2.0,0.000093,0.000087,125612.0,14.0,3.0,125629.0,0.000068,0.000575,0.000000,0.000000,0.000535,0.000794,0.000000,0.000012,0.0,0.000052,0.000000,0.000000,0.000397,0.000598,0.000000,0.000009,0.0,0.000033,protein_coding,ENSG00000147133,2,5679,38,protein_coding,166111,1.0,2.0,50.800,0.039370,NaN,X,70586114,70752224
8,RSF1,ENST00000308488,620,756.71,0.81933,0.000040,9552,206.0,310.49,0.66348,3722.0,259,265.17,0.97673,0.000013,2603,0.0,0.000004,846.0,67.830,1.0,1.142700e-27,1.716200e-11,0.000000,0.882,1.083,0.766,0.876,0.000,0.044,NaN,0.297860,1.7661,7.6318,8.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,protein_coding,ENSG00000048649,2,4323,16,protein_coding,161023,1.0,0.0,46.996,0.000000,NaN,11,77371041,77532063
9,NCKAP1,ENST00000360982,291,580.53,0.50127,0.000029,7483,56.0,154.07,0.36346,2017.0,194,197.96,0.98000,0.000010,2051,0.0,0.000004,850.0,67.231,1.0,1.972600e-27,2.147300e-11,0.000000,0.871,1.104,0.455,0.552,0.000,0.044,NaN,0.221170,4.2701,7.5981,9.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,protein_coding,ENSG00000061676,2,3402,32,protein_coding,129744,1.0,0.0,50.723,0.000000,NaN,2,183773843,183903586

Now add the missense and loss-of-function z-scores to the main dataframe.

In [16]:
mis_oe = pd.Series(constraint.oe_mis.values, index = constraint.gene).to_dict()
lof_oe = pd.Series(constraint.oe_lof.values, index = constraint.gene).to_dict()
mis_z = pd.Series(constraint.mis_z.values, index = constraint.gene).to_dict()
lof_z = pd.Series(constraint.lof_z.values, index = constraint.gene).to_dict()

In [17]:
data['mis_oe'] = data['annotation'].map(mis_oe)
data['lof_oe'] = data['annotation'].map(lof_oe)
data['mis_z'] = data['annotation'].map(mis_z)
data['lof_z'] = data['annotation'].map(lof_z)

In [18]:
data.head(10)

,chrom,pos,ref_allele,altai_gt,chagyrskaya_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,delta_max,ag_pos,al_pos,dg_pos,dl_pos,variant_type,altai_gt_boolean,chagyrskaya_gt_boolean,denisovan_gt_boolean,vindija_gt_boolean,distribution,mis_oe,lof_oe,mis_z,lof_z
0,chr1,739130,T,0/0,./.,./.,0/1,TA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-7,-36,-35,-31,indel,FALSE,FALSE,FALSE,TRUE,Vindija,NaN,NaN,NaN,NaN
1,chr1,739130,T,0/1,./.,./.,0/0,TAA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-31,-36,-7,-31,indel,TRUE,FALSE,FALSE,FALSE,Altai,NaN,NaN,NaN,NaN
1169649,chr1,861808,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.01,0.0,0.01,-29,-27,24,-20,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.5082,0.89656,-3.43610,0.47484
1169650,chr1,861808,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,0.00,48,-14,-46,-14,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.2217,0.73515,-0.64548,0.49579
1169651,chr1,862072,C,1/1,1/1,0/0,0/1,T,SAMD11,0.0,0.0,0.00,0.0,0.00,3,28,-38,41,snv,TRUE,TRUE,FALSE,TRUE,Neanderthal,1.5082,0.89656,-3.43610,0.47484
1169652,chr1,862072,C,1/1,1/1,0/0,0/1,T,AL645608.1,0.0,0.0,0.00,0.0,0.00,-6,-50,24,-48,snv,TRUE,TRUE,FALSE,TRUE,Neanderthal,1.2217,0.73515,-0.64548,0.49579
1169653,chr1,862093,T,0/0,0/0,1/1,0/0,C,SAMD11,0.0,0.0,0.00,0.0,0.00,7,14,-15,34,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.5082,0.89656,-3.43610,0.47484
1169654,chr1,862093,T,0/0,0/0,1/1,0/0,C,AL645608.1,0.0,0.0,0.00,0.0,0.00,-34,48,49,3,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.2217,0.73515,-0.64548,0.49579
1169655,chr1,862124,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.00,0.0,0.00,-24,26,-11,3,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.5082,0.89656,-3.43610,0.47484
1169656,chr1,862124,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,0.00,17,-14,-28,35,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.2217,0.73515,-0.64548,0.49579

In [19]:
len(data)

2107054

Let's add per variant phyloP data.

In [20]:
variant_phyloP_header = ['chrom','start','pos','phyloP']
variant_phyloP = pd.read_csv('../../data/annotations/all_variant_sites_hg19_phyloP.bed', sep = '\t', names = variant_phyloP_header)
variant_phyloP.head(10)

  chrom   start     pos  phyloP
0  chr1  739129  739130   0.155
1  chr1  739129  739130   0.155
2  chr1  861807  861808  -0.683
3  chr1  861807  861808  -0.683
4  chr1  862071  862072   0.197
5  chr1  862071  862072   0.197
6  chr1  862092  862093  -1.042
7  chr1  862092  862093  -1.042
8  chr1  862123  862124  -3.750
9  chr1  862123  862124  -3.750

In [21]:
data = pd.merge(data, variant_phyloP[['chrom','pos','phyloP']], on = ['chrom','pos'], how = 'left', indicator = False)
data.head(10)

,chrom,pos,ref_allele,altai_gt,chagyrskaya_gt,denisovan_gt,vindija_gt,alt_allele,annotation,ag_delta,al_delta,dg_delta,dl_delta,delta_max,ag_pos,al_pos,dg_pos,dl_pos,variant_type,altai_gt_boolean,chagyrskaya_gt_boolean,denisovan_gt_boolean,vindija_gt_boolean,distribution,mis_oe,lof_oe,mis_z,lof_z,phyloP
0,chr1,739130,T,0/0,./.,./.,0/1,TA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-7,-36,-35,-31,indel,FALSE,FALSE,FALSE,TRUE,Vindija,NaN,NaN,NaN,NaN,0.155
1,chr1,739130,T,0/0,./.,./.,0/1,TA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-7,-36,-35,-31,indel,FALSE,FALSE,FALSE,TRUE,Vindija,NaN,NaN,NaN,NaN,0.155
2,chr1,739130,T,0/1,./.,./.,0/0,TAA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-31,-36,-7,-31,indel,TRUE,FALSE,FALSE,FALSE,Altai,NaN,NaN,NaN,NaN,0.155
3,chr1,739130,T,0/1,./.,./.,0/0,TAA,AL669831.1,0.0,0.0,0.00,0.0,0.00,-31,-36,-7,-31,indel,TRUE,FALSE,FALSE,FALSE,Altai,NaN,NaN,NaN,NaN,0.155
4,chr1,861808,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.01,0.0,0.01,-29,-27,24,-20,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.5082,0.89656,-3.43610,0.47484,-0.683
5,chr1,861808,A,0/0,0/0,1/1,0/0,G,SAMD11,0.0,0.0,0.01,0.0,0.01,-29,-27,24,-20,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.5082,0.89656,-3.43610,0.47484,-0.683
6,chr1,861808,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,0.00,48,-14,-46,-14,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.2217,0.73515,-0.64548,0.49579,-0.683
7,chr1,861808,A,0/0,0/0,1/1,0/0,G,AL645608.1,0.0,0.0,0.00,0.0,0.00,48,-14,-46,-14,snv,FALSE,FALSE,TRUE,FALSE,Denisovan,1.2217,0.73515,-0.64548,0.49579,-0.683
8,chr1,862072,C,1/1,1/1,0/0,0/1,T,SAMD11,0.0,0.0,0.00,0.0,0.00,3,28,-38,41,snv,TRUE,TRUE,FALSE,TRUE,Neanderthal,1.5082,0.89656,-3.43610,0.47484,0.197
9,chr1,862072,C,1/1,1/1,0/0,0/1,T,SAMD11,0.0,0.0,0.00,0.0,0.00,3,28,-38,41,snv,TRUE,TRUE,FALSE,TRUE,Neanderthal,1.5082,0.89656,-3.43610,0.47484,0.197

In [22]:
len(data)

2358420

In [23]:
data = data.drop_duplicates()
len(data)

2107041

Let's reorder the dataframe a bit to group similar columns.

In [24]:
data = data[['chrom','pos','ref_allele','alt_allele','variant_type','altai_gt','chagyrskaya_gt','denisovan_gt','vindija_gt','altai_gt_boolean','chagyrskaya_gt_boolean','denisovan_gt_boolean','vindija_gt_boolean','distribution','annotation','mis_oe','mis_z','lof_oe','lof_z','phyloP','ag_delta','al_delta','dg_delta','dl_delta','delta_max','ag_pos','al_pos','dg_pos','dl_pos']]

Now let's export this dataframe as we will use it again in downstream analyses.

In [25]:
data.to_csv('../../data/dataframes/archaic_data_with_constraint.txt', sep = '\t', header = True, index = False)